<?php
// install.php - SalesCalls CRM Installation Script
// Run this file once to set up the database and default admin

session_start();

// Prevent installation if already completed
if (file_exists('includes/installed.lock')) {
    die('Installation already completed. Delete includes/installed.lock to reinstall.');
}

$step = isset($_GET['step']) ? (int)$_GET['step'] : 1;
$error = '';
$success = '';

// Step 1: Requirements check
function checkRequirements() {
    $requirements = [
        'php_version' => version_compare(PHP_VERSION, '7.4.0', '>='),
        'pdo_mysql' => extension_loaded('pdo_mysql'),
        'mysqli' => extension_loaded('mysqli'),
        'openssl' => extension_loaded('openssl'),
        'json' => extension_loaded('json'),
        'fileinfo' => extension_loaded('fileinfo'),
        'writable_config' => is_writable('includes'),
        'writable_uploads' => is_writable('temp_uploads') || mkdir('temp_uploads', 0755, true),
        'writable_email_config' => is_writable('includes') || touch('includes/email_config.php')
    ];
    
    $all_pass = true;
    foreach ($requirements as $check => $passed) {
        if (!$passed) $all_pass = false;
    }
    
    return ['all_pass' => $all_pass, 'details' => $requirements];
}

// Step 2: Database configuration
if ($_SERVER['REQUEST_METHOD'] === 'POST' && isset($_POST['test_db'])) {
    $host = trim($_POST['db_host'] ?? 'localhost');
    $port = (int)($_POST['db_port'] ?? 3306);
    $name = trim($_POST['db_name'] ?? '');
    $user = trim($_POST['db_user'] ?? '');
    $pass = $_POST['db_pass'] ?? '';
    
    try {
        $pdo = new PDO("mysql:host=$host;port=$port;charset=utf8mb4", $user, $pass);
        $pdo->setAttribute(PDO::ATTR_ERRMODE, PDO::ERRMODE_EXCEPTION);
        
        // Check if database exists, create if not
        $stmt = $pdo->query("SELECT SCHEMA_NAME FROM INFORMATION_SCHEMA.SCHEMATA WHERE SCHEMA_NAME = " . $pdo->quote($name));
        if (!$stmt->fetch()) {
            $pdo->exec("CREATE DATABASE `$name` CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci");
        }
        
        // Store credentials in session for next step
        $_SESSION['db_config'] = [
            'host' => $host,
            'port' => $port,
            'name' => $name,
            'user' => $user,
            'pass' => $pass
        ];
        
        $success = "Database connection successful!";
        $step = 3;
    } catch (PDOException $e) {
        $error = "Connection failed: " . $e->getMessage();
    }
}

// Step 3: Run installation
if ($_SERVER['REQUEST_METHOD'] === 'POST' && isset($_POST['install'])) {
    $admin_email = trim($_POST['admin_email'] ?? '');
    $admin_password = $_POST['admin_password'] ?? '';
    $admin_name = trim($_POST['admin_name'] ?? 'Administrator');
    $confirm_password = $_POST['confirm_password'] ?? '';
    
    if (empty($admin_email) || empty($admin_password)) {
        $error = 'Admin email and password are required.';
    } elseif ($admin_password !== $confirm_password) {
        $error = 'Passwords do not match.';
    } elseif (strlen($admin_password) < 8) {
        $error = 'Password must be at least 8 characters.';
    } elseif (!filter_var($admin_email, FILTER_VALIDATE_EMAIL)) {
        $error = 'Valid email is required.';
    } else {
        $db = $_SESSION['db_config'];
        
        try {
            // Connect to database
            $pdo = new PDO(
                "mysql:host={$db['host']};port={$db['port']};dbname={$db['name']};charset=utf8mb4",
                $db['user'],
                $db['pass']
            );
            $pdo->setAttribute(PDO::ATTR_ERRMODE, PDO::ERRMODE_EXCEPTION);
            
            // Read and execute schema.sql
            $schema = file_get_contents('database/schema.sql');
            $pdo->exec($schema);
            
            // Create default admin
            $hashed_password = password_hash($admin_password, PASSWORD_DEFAULT);
            $stmt = $pdo->prepare("INSERT INTO users (name, email, password_hash, role, setup_completed, created_at) VALUES (?, ?, ?, 'admin', 0, NOW())");
            $stmt->execute([$admin_name, $admin_email, $hashed_password]);
            
            // Create config file
            $config_content = "<?php\n";
            $config_content .= "// Database Configuration - Generated by Installer\n";
            $config_content .= "define('DB_HOST', '" . addslashes($db['host']) . "');\n";
            $config_content .= "define('DB_PORT', " . $db['port'] . ");\n";
            $config_content .= "define('DB_NAME', '" . addslashes($db['name']) . "');\n";
            $config_content .= "define('DB_USER', '" . addslashes($db['user']) . "');\n";
            $config_content .= "define('DB_PASS', '" . addslashes($db['pass']) . "');\n\n";
            $config_content .= "// Application Settings\n";
            $config_content .= "define('APP_NAME', 'SalesCalls CRM');\n";
            $config_content .= "define('APP_URL', '" . addslashes((isset($_SERVER['HTTPS']) ? 'https://' : 'http://') . $_SERVER['HTTP_HOST'] . rtrim(dirname($_SERVER['SCRIPT_NAME']), '/')) . "');\n";
            $config_content .= "define('APP_SECRET_KEY', '" . bin2hex(random_bytes(32)) . "');\n";
            $config_content .= "define('TIMEZONE', 'UTC');\n\n";
            $config_content .= "// PDO Connection\n";
            $config_content .= "\$pdo = new PDO(\n";
            $config_content .= "    'mysql:host=' . DB_HOST . ';port=' . DB_PORT . ';dbname=' . DB_NAME . ';charset=utf8mb4',\n";
            $config_content .= "    DB_USER,\n";
            $config_content .= "    DB_PASS,\n";
            $config_content .= "    [PDO::ATTR_ERRMODE => PDO::ERRMODE_EXCEPTION]\n";
            $config_content .= ");\n";
            
            file_put_contents('includes/config.php', $config_content);
            
            // Create empty email_config.php
            file_put_contents('includes/email_config.php', "<?php\n// Email configuration will be added via admin panel\n");
            
            // Create installation lock file
            file_put_contents('includes/installed.lock', date('Y-m-d H:i:s'));
            
            $success = "Installation completed successfully!";
            $step = 4;
            
        } catch (PDOException $e) {
            $error = "Installation failed: " . $e->getMessage();
        }
    }
}

// HTML Header
?><!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Install SalesCalls CRM</title>
    <style>
        * { box-sizing: border-box; margin: 0; padding: 0; }
        body {
            font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, Oxygen, Ubuntu, sans-serif;
            background: linear-gradient(135deg, #1130b8 0%, #259993 100%);
            min-height: 100vh;
            display: flex;
            align-items: center;
            justify-content: center;
            padding: 20px;
        }
        .installer {
            max-width: 800px;
            width: 100%;
            background: white;
            border-radius: 10px;
            box-shadow: 0 20px 60px rgba(0,0,0,0.3);
            overflow: hidden;
        }
        .header {
            background: #f8f9fa;
            padding: 30px;
            text-align: center;
            border-bottom: 1px solid #e9ecef;
        }
        .header h1 { color: #333; margin-bottom: 10px; }
        .header p { color: #666; }
        .steps {
            display: flex;
            background: #f8f9fa;
            border-bottom: 1px solid #e9ecef;
        }
        .step {
            flex: 1;
            text-align: center;
            padding: 15px;
            color: #999;
            border-right: 1px solid #e9ecef;
        }
        .step:last-child { border-right: none; }
        .step.active {
            background: white;
            color: #667eea;
            font-weight: 600;
        }
        .step.completed {
            color: #28a745;
        }
        .content {
            padding: 30px;
        }
        .form-group {
            margin-bottom: 20px;
        }
        label {
            display: block;
            margin-bottom: 5px;
            font-weight: 500;
            color: #333;
        }
        input, select {
            width: 100%;
            padding: 10px;
            border: 1px solid #ddd;
            border-radius: 5px;
            font-size: 16px;
        }
        input:focus {
            outline: none;
            border-color: #667eea;
            box-shadow: 0 0 0 2px rgba(102,126,234,0.1);
        }
        .btn {
            display: inline-block;
            padding: 12px 30px;
            background: #667eea;
            color: white;
            border: none;
            border-radius: 5px;
            font-size: 16px;
            font-weight: 500;
            cursor: pointer;
            text-decoration: none;
            transition: background 0.3s;
        }
        .btn:hover { background: #5a67d8; }
        .btn-secondary {
            background: #718096;
        }
        .btn-secondary:hover { background: #4a5568; }
        .alert {
            padding: 12px 15px;
            border-radius: 5px;
            margin-bottom: 20px;
        }
        .alert-error {
            background: #f8d7da;
            color: #721c24;
            border: 1px solid #f5c6cb;
        }
        .alert-success {
            background: #d4edda;
            color: #155724;
            border: 1px solid #c3e6cb;
        }
        .requirements-list {
            list-style: none;
            margin: 20px 0;
        }
        .requirements-list li {
            padding: 10px;
            border-bottom: 1px solid #eee;
            display: flex;
            align-items: center;
        }
        .requirements-list li:last-child { border-bottom: none; }
        .badge {
            display: inline-block;
            padding: 3px 8px;
            border-radius: 12px;
            font-size: 12px;
            font-weight: 600;
            margin-left: 10px;
        }
        .badge-success {
            background: #d4edda;
            color: #155724;
        }
        .badge-error {
            background: #f8d7da;
            color: #721c24;
        }
        .info-box {
            background: #e7f3ff;
            border-left: 4px solid #2196F3;
            padding: 15px;
            margin: 20px 0;
            border-radius: 4px;
        }
        .btn-group {
            display: flex;
            gap: 10px;
            margin-top: 20px;
        }
        .login-link {
            display: inline-block;
            margin-top: 20px;
            color: #667eea;
            text-decoration: none;
        }
        .login-link:hover { text-decoration: underline; }
    </style>
</head>
<body>
    <div class="installer">
        <div class="header">
            <h1>SalesCalls CRM Installation</h1>
            <p>Welcome to the installation wizard. Let's get your CRM set up.</p>
        </div>
        
        <div class="steps">
            <div class="step <?= $step >= 1 ? 'active' : '' ?> <?= $step > 1 ? 'completed' : '' ?>">1. Requirements</div>
            <div class="step <?= $step >= 2 ? 'active' : '' ?> <?= $step > 2 ? 'completed' : '' ?>">2. Database</div>
            <div class="step <?= $step >= 3 ? 'active' : '' ?> <?= $step > 3 ? 'completed' : '' ?>">3. Admin Account</div>
            <div class="step <?= $step >= 4 ? 'active' : '' ?>">4. Complete</div>
        </div>
        
        <div class="content">
            <?php if ($error): ?>
                <div class="alert alert-error"><?= htmlspecialchars($error) ?></div>
            <?php endif; ?>
            
            <?php if ($success): ?>
                <div class="alert alert-success"><?= htmlspecialchars($success) ?></div>
            <?php endif; ?>
            
            <?php if ($step === 1): ?>
                <?php $reqs = checkRequirements(); ?>
                <h2>System Requirements Check</h2>
                
                <ul class="requirements-list">
                    <li>
                        PHP Version >= 7.4.0 (Current: <?= PHP_VERSION ?>)
                        <?php if ($reqs['details']['php_version']): ?>
                            <span class="badge badge-success">✓</span>
                        <?php else: ?>
                            <span class="badge badge-error">✗</span>
                        <?php endif; ?>
                    </li>
                    <li>
                        PDO MySQL Extension
                        <?php if ($reqs['details']['pdo_mysql']): ?>
                            <span class="badge badge-success">✓</span>
                        <?php else: ?>
                            <span class="badge badge-error">✗</span>
                        <?php endif; ?>
                    </li>
                    <li>
                        MySQLi Extension
                        <?php if ($reqs['details']['mysqli']): ?>
                            <span class="badge badge-success">✓</span>
                        <?php else: ?>
                            <span class="badge badge-error">✗</span>
                        <?php endif; ?>
                    </li>
                    <li>
                        OpenSSL Extension
                        <?php if ($reqs['details']['openssl']): ?>
                            <span class="badge badge-success">✓</span>
                        <?php else: ?>
                            <span class="badge badge-error">✗</span>
                        <?php endif; ?>
                    </li>
                    <li>
                        JSON Extension
                        <?php if ($reqs['details']['json']): ?>
                            <span class="badge badge-success">✓</span>
                        <?php else: ?>
                            <span class="badge badge-error">✗</span>
                        <?php endif; ?>
                    </li>
                    <li>
                        FileInfo Extension
                        <?php if ($reqs['details']['fileinfo']): ?>
                            <span class="badge badge-success">✓</span>
                        <?php else: ?>
                            <span class="badge badge-error">✗</span>
                        <?php endif; ?>
                    </li>
                    <li>
                        includes/ directory writable
                        <?php if ($reqs['details']['writable_config']): ?>
                            <span class="badge badge-success">✓</span>
                        <?php else: ?>
                            <span class="badge badge-error">✗</span>
                        <?php endif; ?>
                    </li>
                    <li>
                        temp_uploads/ directory writable
                        <?php if ($reqs['details']['writable_uploads']): ?>
                            <span class="badge badge-success">✓</span>
                        <?php else: ?>
                            <span class="badge badge-error">✗</span>
                        <?php endif; ?>
                    </li>
                </ul>
                
                <?php if ($reqs['all_pass']): ?>
                    <div class="info-box">
                        ✅ All requirements are met. You can proceed with the installation.
                    </div>
                    <a href="?step=2" class="btn">Next Step: Database Setup →</a>
                <?php else: ?>
                    <div class="alert alert-error">
                        Please fix the missing requirements before proceeding.
                    </div>
                <?php endif; ?>
                
            <?php elseif ($step === 2): ?>
                <h2>Database Configuration</h2>
                <p>Enter your database connection details.</p>
                
                <form method="post">
                    <div class="form-group">
                        <label for="db_host">Database Host</label>
                        <input type="text" id="db_host" name="db_host" value="localhost" required>
                    </div>
                    
                    <div class="form-group">
                        <label for="db_port">Port</label>
                        <input type="number" id="db_port" name="db_port" value="3306" required>
                    </div>
                    
                    <div class="form-group">
                        <label for="db_name">Database Name</label>
                        <input type="text" id="db_name" name="db_name" required>
                    </div>
                    
                    <div class="form-group">
                        <label for="db_user">Database Username</label>
                        <input type="text" id="db_user" name="db_user" required>
                    </div>
                    
                    <div class="form-group">
                        <label for="db_pass">Database Password</label>
                        <input type="password" id="db_pass" name="db_pass">
                    </div>
                    
                    <div class="btn-group">
                        <a href="?step=1" class="btn btn-secondary">← Back</a>
                        <button type="submit" name="test_db" class="btn">Test Connection →</button>
                    </div>
                </form>
                
            <?php elseif ($step === 3): ?>
                <h2>Create Admin Account</h2>
                <p>Set up the administrator account for your CRM.</p>
                
                <form method="post">
                    <div class="form-group">
                        <label for="admin_name">Admin Name</label>
                        <input type="text" id="admin_name" name="admin_name" value="Administrator" required>
                    </div>
                    
                    <div class="form-group">
                        <label for="admin_email">Admin Email</label>
                        <input type="email" id="admin_email" name="admin_email" required>
                    </div>
                    
                    <div class="form-group">
                        <label for="admin_password">Admin Password (min. 8 characters)</label>
                        <input type="password" id="admin_password" name="admin_password" required minlength="8">
                    </div>
                    
                    <div class="form-group">
                        <label for="confirm_password">Confirm Password</label>
                        <input type="password" id="confirm_password" name="confirm_password" required minlength="8">
                    </div>
                    
                    <div class="info-box">
                        <strong>Note:</strong> You'll be prompted to change these credentials on first login.
                    </div>
                    
                    <div class="btn-group">
                        <a href="?step=2" class="btn btn-secondary">← Back</a>
                        <button type="submit" name="install" class="btn">Install CRM →</button>
                    </div>
                </form>
                
            <?php elseif ($step === 4): ?>
                <h2>Installation Complete!</h2>
                
                <div class="info-box">
                    <strong>🎉 Congratulations!</strong> Your SalesCalls CRM has been successfully installed.
                </div>
                
                <h3>Next Steps:</h3>
                <ol style="margin: 20px 0 20px 20px;">
                    <li>Login with your admin credentials</li>
                    <li>Complete the setup wizard (change password, set email)</li>
                    <li>Configure SMTP settings in Admin → SMTP Settings</li>
                    <li>Create your first project and start adding leads</li>
                </ol>
                
                <div class="alert alert-warning" style="background: #fff3cd; color: #856404; border-color: #ffeeba;">
                    <strong>Security Note:</strong> For security, we recommend deleting the <code>install.php</code> file now.
                </div>
                
                <a href="login.php" class="btn">Go to Login Page</a>
                
            <?php endif; ?>
        </div>
    </div>
    
    <script>
    // Simple password match validation
    if (document.querySelector('input[name="admin_password"]')) {
        document.querySelector('form').addEventListener('submit', function(e) {
            const pass = document.querySelector('input[name="admin_password"]').value;
            const confirm = document.querySelector('input[name="confirm_password"]').value;
            
            if (pass !== confirm) {
                e.preventDefault();
                alert('Passwords do not match!');
            }
        });
    }
    </script>
</body>
</html>