<?php
// email_config.example.php - Example email configuration
// This file is auto-generated by admin/smtp.php
// Default empty values - replace with your actual SMTP settings

define('SMTP_HOST', 'smtp.example.com');
define('SMTP_PORT', 587);
define('SMTP_USER', 'your-email@example.com');
define('SMTP_PASS', 'your-password');
define('SMTP_ENCRYPTION', 'tls');
define('FROM_EMAIL', 'noreply@example.com');
define('FROM_NAME', 'SalesCalls CRM');